//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKiralama.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracBilgisi
    {
        public int aracID { get; set; }
        public string aracMarka { get; set; }
        public string aracDepo { get; set; }
        public string aracVites { get; set; }
        public Nullable<decimal> aracFiyat { get; set; }
        public Nullable<byte> aracKapisi { get; set; }
        public Nullable<byte> aracKoltuk { get; set; }
        public string aracBagaj { get; set; }
        public string aracTipi { get; set; }
        public string aracModel { get; set; }
        public string ehliyetSinif { get; set; }
        public Nullable<int> modelID { get; set; }
        public Nullable<int> modelyili { get; set; }
        public string ımage { get; set; }
    }
}
