//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKiralama.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracRezervasyon
    {
        public int rezervasyonID { get; set; }
        public string istasyonAlisYeri { get; set; }
        public string İstasyonTeslimYeri { get; set; }
        public Nullable<System.DateTime> İstasyonAlisTarihi { get; set; }
        public Nullable<System.DateTime> istasyonBitisTarihi { get; set; }
        public string rezervasyondurum { get; set; }
        public int KulllanıcıID { get; set; }
        public int aracID { get; set; }
        public string İptalMi { get; set; }
        public Nullable<System.DateTime> İptalTarihi { get; set; }
        public Nullable<decimal> Ucret { get; set; }
    }
}
