//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKiralama.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanıcı
    {
        public int KullanıcıID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Email { get; set; }
        public string Sifre { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string KanGrup { get; set; }
        public string EhliyetSinifi { get; set; }
        public int YetkiID { get; set; }
        public string Image { get; set; }
    
        public virtual Yetki Yetki { get; set; }
    }
}
