//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKiralama.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CKiralamaEntities8 : DbContext
    {
        public CKiralamaEntities8()
            : base("name=CKiralamaEntities8")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AracBilgisi> AracBilgisi { get; set; }
        public virtual DbSet<AracRezervasyon> AracRezervasyon { get; set; }
        public virtual DbSet<İstasyonYeri> İstasyonYeri { get; set; }
        public virtual DbSet<Kullanıcı> Kullanıcı { get; set; }
        public virtual DbSet<Marka> Marka { get; set; }
        public virtual DbSet<Model> Model { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Ucret> Ucret { get; set; }
        public virtual DbSet<Yetki> Yetki { get; set; }
    }
}
