//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKiralama.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ucret
    {
        public int TipID { get; set; }
        public Nullable<int> kartno { get; set; }
        public Nullable<int> cvv { get; set; }
        public Nullable<System.DateTime> sonkTarih { get; set; }
    }
}
